# Configuration des tests pour le profil clan_background_color (basé sur README.md)
tests:
  # - name: "exemple kill the cloud"
  #   description: Test clan slide
  #   command_args:
  #     - --set TEXT2="kill the cloud"
  #     - --set TEXT3="Build Your Own Darknet"
  #     - --set TEXT4="Discover the simplest way to re-enter independent computing"
  #     - --set TEXT5="with our framework. Placing control directly at your fingertips."
