# Configuration des tests pour le profil debug (basé sur README.md)
tests:
  - name: "exemple debug complet"
    description: "Test basé sur l'exemple du README avec TEXT33-35"
    expected_files: ["output.png"]
    command_args:
      - "--set TEXT33=THE"
      - "--set TEXT33_EFFECTS_BEFORE=-stroke none"
      - "--set TEXT33_GEOMETRY=+0-64"
      - "--set TEXT34=debug"
      - "--set TEXT34_FG=#FFD300"
      - "--set TEXT34_FONT_SIZE=96"
      - "--set TEXT34_GEOMETRY=+0-0"
      - "--set TEXT35=profile"
      - "--set TEXT35_GEOMETRY=+0+64"
