# Configuration des tests pour le profil user_post (basé sur README.md)
tests:
  - name: "exemple user post bleu"
    description: "Test basé sur l'exemple principal du README"
    expected_files: ["output.png"]
    command_args:
      - "--set TEXT2=DEVOPS"
      - "--set TEXT3=BRUNO ADELÉ"
      - "--set TEXT4=SLIDE GENERATOR"
      - "--set TEXT5=Generate clean, impactful slides"
      - "--set TEXT6=for your social media posts in seconds"
      - "--set IMG99=https://raw.githubusercontent.com/badele/slide-generator/refs/heads/main/bruno_avatar_128.png"
      
  - name: "exemple avec background personnalisé"
    description: "Test avec image de fond personnalisée"
    expected_files: ["output.png"]
    command_args:
      - "--set IMG1=/tmp/test_bg.png"
      - "--set TEXT2=DEVOPS"
      - "--set TEXT3=BRUNO ADELÉ"
      - "--set TEXT4=SLIDE GENERATOR"
      - "--set TEXT5=Generate clean, impactful slides"
      - "--set TEXT6=for your social media posts in seconds"
      - "--set IMG99=https://raw.githubusercontent.com/badele/slide-generator/refs/heads/main/bruno_avatar_128.png"
      
  - name: "exemple avec effets texte"
    description: "Test avec effets de texte avancés"
    expected_files: ["output.png"]
    command_args:
      - "--set TEXT2=DEVOPS"
      - "--set TEXT3=BRUNO ADELÉ"
      - "--set TEXT4=SLIDE GENERATOR"
      - "--set TEXT5=Generate clean, impactful slides"
      - "--set TEXT5_BG=#FFFFFF"
      - "--set TEXT5_FG=#000000"
      - "--set TEXT5_EFFECTS=-trim -bordercolor '#FFFFFF' -border 5x5"
      - "--set TEXT6=for your social media posts in seconds"
      - "--set TEXT6_BG=#FFFFFF"
      - "--set TEXT6_FG=#000000"
      - "--set TEXT6_EFFECTS=-trim -bordercolor '#FFFFFF' -border 5x5"
      - "--set IMG99=https://raw.githubusercontent.com/badele/slide-generator/refs/heads/main/bruno_avatar_128.png"