name: Tests

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install Nix
      uses: nixbuild/nix-quick-install-action@v32
      
    - name: Setup Nix cache
      uses: cachix/cachix-action@v16
      with:
        name: nixpkgs-unfree
        
    - name: Download and install Next Art font
      run: |
        mkdir -p $HOME/.local/share/fonts
        curl -o nextart.zip "https://dl.dafont.com/dl/?f=next_art"
        unzip nextart.zip -d $HOME/.local/share/fonts/
        fc-cache -fv
        
    - name: Enter Nix development shell and run tests
      run: |
        nix develop --command just test
